#!/usr/bin/env bash
#
# bootstrap installs things.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd)/dotfiles

set -e

echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

link_file () {
  ln -s "$1" "$2"
  success "linked $1 to $2"
}

install_dotfiles () {
  info 'installing dotfiles'

  for src in $(find "$DOTFILES_ROOT/" -maxdepth 2 -name 'stow')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    echo "$src" "$dst"
  done
}

run_installers () {
  # find the installers and run them iteratively
  echo Installing stuff...
  find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
}

run_installers
install_dotfiles

echo ''
echo '  All installed!'
